### ISSUE TITLE
[BUG] Color Theme Dropdown Menu 

### ISSUE THREAD

**Issue by NekoJar** [ab-azmi/capek-kuliah#35]
Style goes off when opened the color theme dropdown menu:
https://github.com/user-attachments/assets/725fea37-81dc-43ff-82f5-8260b5e5d4f8

**Comment by ab-azmi** [comment]
Oke makasih infonya

Pada Rab, 6 Nov 2024 18.14, zharfanhkm ***@***.***> menulis:
